//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Продукты_Заказов = new HashSet<Продукты_Заказов>();
        }
    
        public int PK_id_Заказ { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public Nullable<int> FK_id_Пункт_Выдачи { get; set; }
        public string ФИО_клиента { get; set; }
        public Nullable<int> Код_для_получения { get; set; }
        public Nullable<int> Статус_заказа { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Пункты_Выдачи Пункты_Выдачи { get; set; }
        public virtual Статусы_Заказа Статусы_Заказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продукты_Заказов> Продукты_Заказов { get; set; }
    }
}
