//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int PK_id_Пользователь { get; set; }
        public string Фамилия { get; set; }
        public string Имя_отчество { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int FK_id_Роль { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
