//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукты()
        {
            this.Продукты_Заказов = new HashSet<Продукты_Заказов>();
        }
    
        public int PK_id_Продукт { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public Nullable<int> Размер_максимально_возможной_скидки { get; set; }
        public string Производитель { get; set; }
        public Nullable<int> FK_id_Поставщик { get; set; }
        public int FK_id_Категория_Продукта { get; set; }
        public Nullable<int> Действующая_скидка { get; set; }
        public Nullable<int> Колво_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    
        public virtual Категории_Продуктов Категории_Продуктов { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продукты_Заказов> Продукты_Заказов { get; set; }
    }
}
