//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукты_Заказов
    {
        public int PK_id_Продукт_Заказа { get; set; }
        public int FK_id_Продукт { get; set; }
        public int FK_id_Заказ { get; set; }
        public int Количество { get; set; }
        public Nullable<System.DateTime> Дата_Доставки { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Продукты Продукты { get; set; }
    }
}
